"""Type-8 (lossless mu-law) shorten with BITSHIFT — committed synthetic fixture.

``tests/fixtures/ulaw_bitshift.shn`` is a type-8 shorten stream whose sorted
codes were snapped to multiples of 8, so the encoder emits FN_BITSHIFT blocks
(shift 0..3). ``ulaw_bitshift.ulaw`` is the ground-truth mu-law byte stream.
Both are synthetic (generated by tools/make_ulaw_bitshift_fixture.py), so this
runs in CI without the license-restricted CALLHOME file used by the local test.

bitshift on type-8 is a non-linear remap in mu-law code space; getting it wrong
corrupts loud regions, so byte-exact reconstruction is the assertion.
"""

from __future__ import annotations

import os

from mercator import shorten

FIX = os.path.join(os.path.dirname(os.path.abspath(__file__)), "fixtures")


def test_ulaw_bitshift_decodes_to_ground_truth():
    with open(os.path.join(FIX, "ulaw_bitshift.shn"), "rb") as f:
        values, kind, nchan = shorten.decode(f.read())
    assert kind == "ulaw"
    assert nchan == 1
    with open(os.path.join(FIX, "ulaw_bitshift.ulaw"), "rb") as f:
        assert bytes(values) == f.read()


def test_ulaw_bitshift_fixture_actually_uses_bitshift():
    """Guard against the fixture degrading to all bitshift=0 blocks."""
    with open(os.path.join(FIX, "ulaw_bitshift.shn"), "rb") as f:
        data = f.read()
    br = shorten._BitReader(data, 4)
    br.pos += 1  # version byte
    for _ in range(6):  # ftype, nchan, blocksize, maxnlpc, nmean, nskip
        br.ulong()
    blocksize = 256
    max_shift = 0
    while True:
        fn = br.uvar(shorten._FNSIZE)
        if fn == shorten._FN_QUIT:
            break
        if fn == shorten._FN_BLOCKSIZE:
            blocksize = br.ulong(); continue
        if fn == shorten._FN_BITSHIFT:
            max_shift = max(max_shift, br.uvar(shorten._BITSHIFTSIZE)); continue
        if fn == shorten._FN_VERBATIM:
            for _ in range(br.uvar(shorten._VERBATIM_CKSIZE)):
                br.uvar(shorten._VERBATIM_BYTE)
            continue
        if fn == shorten._FN_QLPC:
            k = br.uvar(shorten._ENERGYSIZE) + 1
            order = br.uvar(shorten._LPCQSIZE)
            for _ in range(order):
                br.var(shorten._LPC_QUANT + 1)
            for _ in range(blocksize):
                br.var(k)
            continue
        if fn == shorten._FN_ZERO:
            continue
        k = br.uvar(shorten._ENERGYSIZE) + 1
        for _ in range(blocksize):
            br.var(k)
    assert max_shift >= 4, f"fixture max bitshift {max_shift} < 4"
