"""QLPC (LPC-predicted) shorten blocks — self-contained, committed fixture.

``tests/fixtures/qlpc_ar2.shn`` is a shorten stream of a synthetic resonant
AR(2) signal, encoded with ``shorten -p 3`` so it contains real FN_QLPC blocks
(orders 2 and 3). ``qlpc_ar2.wav`` is the ground-truth PCM that was encoded.
Both are synthetic (no corpus license), generated by tools/make_qlpc_fixture.py.

The decoder must reconstruct the ground truth byte-for-byte. This needs no
oracle/encoder at test time, so it runs in CI.
"""

from __future__ import annotations

import os
import struct
import wave

import pytest

from mercator import shorten

FIX = os.path.join(os.path.dirname(os.path.abspath(__file__)), "fixtures")


def _wav(path):
    with wave.open(path, "rb") as w:
        n = w.getnframes() * w.getnchannels()
        return w.getnchannels(), list(struct.unpack("<%dh" % n, w.readframes(w.getnframes())))


@pytest.mark.parametrize("stem", ["qlpc_ar2", "qlpc_ar2_stereo"])
def test_qlpc_decodes_to_ground_truth(stem):
    with open(os.path.join(FIX, stem + ".shn"), "rb") as f:
        values, kind, nchan = shorten.decode(f.read())
    want_nchan, want = _wav(os.path.join(FIX, stem + ".wav"))
    assert kind == "pcm16"
    assert nchan == want_nchan
    assert values == want  # interleaved, byte-exact


def test_qlpc_fixture_actually_uses_lpc_blocks():
    """Guard against the fixture silently degrading to all-polynomial blocks."""
    with open(os.path.join(FIX, "qlpc_ar2.shn"), "rb") as f:
        data = f.read()
    br = shorten._BitReader(data, 4)
    br.pos += 1  # version byte
    for _ in range(6):  # ftype, nchan, blocksize, maxnlpc, nmean, nskip
        br.ulong()
    # (no skip bytes in this fixture)
    blocksize = 256
    seen_qlpc = False
    while True:
        fn = br.uvar(shorten._FNSIZE)
        if fn == shorten._FN_QUIT:
            break
        if fn == shorten._FN_BLOCKSIZE:
            blocksize = br.ulong(); continue
        if fn == shorten._FN_BITSHIFT:
            br.uvar(shorten._BITSHIFTSIZE); continue
        if fn == shorten._FN_VERBATIM:
            for _ in range(br.uvar(shorten._VERBATIM_CKSIZE)):
                br.uvar(shorten._VERBATIM_BYTE)
            continue
        if fn == shorten._FN_QLPC:
            seen_qlpc = True
            k = br.uvar(shorten._ENERGYSIZE) + 1
            order = br.uvar(shorten._LPCQSIZE)
            for _ in range(order):
                br.var(shorten._LPC_QUANT + 1)
            for _ in range(blocksize):
                br.var(k)
            continue
        if fn == shorten._FN_ZERO:
            continue
        # DIFF0..3
        k = br.uvar(shorten._ENERGYSIZE) + 1
        for _ in range(blocksize):
            br.var(k)
    assert seen_qlpc, "fixture no longer contains QLPC blocks"
